server:
  port: 8080
spring:
  application:
    name: OAUTH
  zipkin:
    baseUrl: http://msa-trace.development.svc.cluster.local:9411
  sleuth:
    sampler:
      percentage: 0.2
  http:
    encoding:
      force: true
      charset: UTF-8
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: false
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    leaseRenewalIntervalInSeconds: 3
    leaseExpirationDurationInSeconds: 5
